# Generated by Django 3.2.12 on 2022-11-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0012_alter_subcontractor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyCalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_total_amount', models.IntegerField(null=True)),
                ('profit_price', models.IntegerField()),
                ('platform_price', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agency_calculate', to='business.agency')),
            ],
        ),
    ]
