# Generated by Django 3.2.12 on 2022-11-03 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_gym_agency'),
        ('calculate', '0002_auto_20221102_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorCalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_amount', models.IntegerField(null=True)),
                ('total_price_work', models.IntegerField(null=True)),
                ('total_price_work_labor', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontractor_calculate', to='business.subcontractor')),
            ],
        ),
    ]
