# Generated by Django 3.2.12 on 2022-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0005_auto_20221110_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencycalculate',
            name='state',
            field=models.CharField(default='정산전', max_length=10),
        ),
    ]
