# Generated by Django 3.2.12 on 2022-11-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0006_agencycalculate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorcalculate',
            name='state',
            field=models.CharField(default='정산전', max_length=10),
        ),
    ]
