# Generated by Django 3.2.12 on 2022-11-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0007_subcontractorcalculate_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencycalculate',
            options={'ordering': ('agency',)},
        ),
        migrations.AlterModelOptions(
            name='subcontractorcalculate',
            options={'ordering': ('subcontractor',)},
        ),
    ]
