# Generated by Django 3.2.12 on 2022-11-29 06:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPaymentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date_paid', models.DateTimeField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('price_deduct', models.IntegerField()),
                ('days_deduct', models.IntegerField()),
                ('date_to_pay', models.DateTimeField()),
                ('price_to_pay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassPaymentSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_successes', to='class_payment.classpaymentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ClassPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='class_payment.classpaymentmaster')),
            ],
        ),
    ]
