# Generated by Django 3.2.12 on 2022-11-29 06:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_payment', '0001_initial'),
        ('gym_class', '0001_initial'),

    ]

    operations = [
        migrations.AddField(
            model_name='classpaymentmaster',
            name='class_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_payment_masters', to='gym_class.classmaster'),
        ),
    ]
