# Generated by Django 3.2.12 on 2022-11-29 06:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym_student', '0001_initial'),
        ('class_payment', '0002_classpaymentmaster_class_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpaymentmaster',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_payment_masters', to='gym_student.student'),
        ),
    ]
