# Generated by Django 3.2.12 on 2022-12-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_payment', '0003_classpaymentmaster_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpaymentmaster',
            name='payment_method',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='classpaymentmaster',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='classpaymentmaster',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classpaymentmaster',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='classpaymentmaster',
            name='date_to_pay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
