# Generated by Django 3.2.12 on 2022-12-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_payment', '0007_auto_20221220_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpaymentrequest',
            name='customerName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='classpaymentrequest',
            name='orderName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classpaymentrequest',
            name='requestedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
