# Generated by Django 3.2.12 on 2022-12-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_payment', '0008_auto_20221220_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpaymentmaster',
            name='class_name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
