# Generated by Django 3.2.12 on 2022-12-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_payment', '0009_classpaymentmaster_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpaymentmaster',
            name='order_id',
            field=models.CharField(default='5', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classpaymentmaster',
            name='days_deduct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classpaymentmaster',
            name='price_deduct',
            field=models.IntegerField(default=0),
        ),
    ]
