# Generated by Django 3.2.12 on 2022-12-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_payment', '0010_auto_20221225_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpaymentmaster',
            name='order_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
