# Generated by Django 3.2.12 on 2022-12-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_payment', '0011_alter_classpaymentmaster_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpaymentrequest',
            name='method',
            field=models.CharField(max_length=10),
        ),
    ]
