# Generated by Django 3.2.12 on 2023-01-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_payment', '0012_alter_classpaymentrequest_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpaymentmaster',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
