# Generated by Django 3.2.12 on 2023-01-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_payment', '0013_classpaymentmaster_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpaymentmaster',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
