# Generated by Django 3.2.12 on 2023-04-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_payment', '0014_classpaymentmaster_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpaymentmaster',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
