# Generated by Django 3.2.12 on 2023-06-21 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0085_orderdetail_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0023_auto_20221219_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('date_used', models.DateTimeField(auto_now=True)),
                ('start_of_use', models.DateTimeField(null=True)),
                ('end_of_use', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('coupon_number', models.CharField(max_length=20, null=True)),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('expired_day', models.IntegerField(null=True)),
                ('coupon_message', models.CharField(max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'coupon_masters',
            },
        ),
        migrations.CreateModel(
            name='CsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, null=True)),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=15, null=True)),
                ('is_paid', models.BooleanField(null=True)),
                ('is_shipped', models.BooleanField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=20)),
                ('memo', models.TextField(null=True)),
                ('cs_state', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_requests', to='business.gym')),
                ('order_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_requests', to='order.ordermaster')),
            ],
            options={
                'db_table': 'cs_requests',
            },
        ),
        migrations.CreateModel(
            name='CsRequestContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cs_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqeust_contents', to='cs.csrequest')),
            ],
            options={
                'db_table': 'cs_request_contents',
            },
        ),
        migrations.CreateModel(
            name='CsOrderChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('cs_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_order_change_histories', to='cs.csrequest')),
                ('order_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cs_order_change_histories', to='order.orderdetail')),
                ('order_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cs_order_change_histories', to='order.ordermaster')),
            ],
            options={
                'db_table': 'cs_order_change_histories',
            },
        ),
        migrations.CreateModel(
            name='CouponUseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_number', models.CharField(max_length=20, null=True)),
                ('order_number', models.CharField(max_length=25, unique=True)),
                ('gym_name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('date_used', models.DateTimeField(null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_use_histories', to='cs.coupon')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_use_histories', to='business.gym')),
                ('order_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_use_histories', to='order.ordermaster')),
            ],
            options={
                'db_table': 'coupon_use_histories',
            },
        ),
        migrations.CreateModel(
            name='CouponIssueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_number', models.CharField(max_length=20, null=True)),
                ('gym_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('date_issued', models.DateTimeField(auto_now=True)),
                ('start_of_use', models.DateTimeField(null=True)),
                ('end_of_use', models.DateTimeField(null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_issue_histories', to='cs.coupon')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_issue_histories', to='business.gym')),
            ],
            options={
                'db_table': 'coupon_issue_histories',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='cs.couponmaster'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
