# Generated by Django 3.2.12 on 2023-06-22 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0087_remove_ordermaster_user_address'),
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsRequestChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_reason', models.CharField(max_length=100, null=True)),
                ('picked_receiver', models.CharField(max_length=15, null=True)),
                ('picked_phone', models.CharField(max_length=11, null=True)),
                ('picked_address', models.CharField(max_length=100, null=True)),
                ('picked_detail_address', models.CharField(max_length=100, null=True)),
                ('delivered_receiver', models.CharField(max_length=15, null=True)),
                ('delivered_phone', models.CharField(max_length=11, null=True)),
                ('delivered_address', models.CharField(max_length=100, null=True)),
                ('delivered_detail_address', models.CharField(max_length=100, null=True)),
                ('changed_price', models.IntegerField(null=True)),
                ('is_changed_price_exempt', models.BooleanField(default=False)),
                ('delivery_price', models.IntegerField(null=True)),
                ('is_delivery_price_exempt', models.BooleanField(default=False)),
                ('total_price', models.IntegerField(null=True)),
                ('current_smarter_money', models.IntegerField(null=True)),
                ('after_smarter_money', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cs_request_changes',
            },
        ),
        migrations.CreateModel(
            name='CsRequestRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_reason', models.CharField(max_length=100, null=True)),
                ('receiver', models.CharField(max_length=15, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('detail_address', models.CharField(max_length=100, null=True)),
                ('total_products_price', models.IntegerField(null=True)),
                ('total_refund_delivery_price', models.IntegerField(null=True)),
                ('is_delivery_price_exempt', models.BooleanField(default=False)),
                ('total_refund_price', models.IntegerField(null=True)),
                ('current_smarter_money', models.IntegerField(null=True)),
                ('after_smarter_money', models.IntegerField(null=True)),
                ('memo', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cs_request_refunds',
            },
        ),
        migrations.RenameField(
            model_name='csrequest',
            old_name='is_completed',
            new_name='is_work_completed',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_used',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='couponissuehistory',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='csorderchangehistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='csrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CsRequestRefundDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_quantity', models.IntegerField(null=True)),
                ('refund_price', models.IntegerField(null=True)),
                ('cs_request_refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_details', to='cs.csrequestrefund')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_details', to='order.orderdetail')),
            ],
            options={
                'db_table': 'cs_request_refund_details',
            },
        ),
        migrations.AddField(
            model_name='csrequestrefund',
            name='cs_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='cs.csrequest'),
        ),
        migrations.CreateModel(
            name='CsRequestChangeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_quantity', models.IntegerField(null=True)),
                ('changed_color', models.CharField(max_length=10, null=True)),
                ('changed_size', models.CharField(max_length=10, null=True)),
                ('additional_product_price', models.IntegerField(null=True)),
                ('additional_total_price', models.IntegerField(null=True)),
                ('changed_order_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_change_details', to='order.orderdetail')),
                ('cs_request_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_details', to='cs.csrequestchange')),
                ('old_order_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_change_details', to='order.orderdetail')),
            ],
            options={
                'db_table': 'cs_request_change_details',
            },
        ),
        migrations.AddField(
            model_name='csrequestchange',
            name='cs_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='cs.csrequest'),
        ),
    ]
