# Generated by Django 3.2.12 on 2023-06-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0003_auto_20230622_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrequestrefund',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='csrequestcontents',
            table='cs_request_contents',
        ),
    ]
