# Generated by Django 3.2.12 on 2023-06-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0004_auto_20230622_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csrequest',
            old_name='date_created',
            new_name='date_requested',
        ),
        migrations.RemoveField(
            model_name='csrequest',
            name='request_date',
        ),
    ]
