# Generated by Django 3.2.12 on 2023-06-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0005_auto_20230622_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmaster',
            name='coupon_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
