# Generated by Django 3.2.12 on 2023-06-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0006_alter_couponmaster_coupon_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponmaster',
            name='coupon_number',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
