# Generated by Django 3.2.12 on 2023-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0007_auto_20230623_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmaster',
            old_name='number',
            new_name='count_issued',
        ),
        migrations.AddField(
            model_name='coupon',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_used',
            field=models.DateTimeField(),
        ),
    ]
