# Generated by Django 3.2.12 on 2023-06-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0009_alter_coupon_date_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmaster',
            old_name='count_issued',
            new_name='count_per_issue',
        ),
    ]
