# Generated by Django 3.2.12 on 2023-06-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0010_rename_count_issued_couponmaster_count_per_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmaster',
            old_name='expired_day',
            new_name='expire_day',
        ),
    ]
