# Generated by Django 3.2.12 on 2023-06-27 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0011_rename_expired_day_couponmaster_expire_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csrequestcontents',
            old_name='content',
            new_name='contents',
        ),
    ]
