# Generated by Django 3.2.12 on 2023-06-27 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0012_rename_content_csrequestcontents_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrequestcontents',
            name='cs_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_contents', to='cs.csrequest'),
        ),
    ]
