# Generated by Django 3.2.12 on 2023-06-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0013_alter_csrequestcontents_cs_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrequest',
            name='category',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='csrequest',
            name='cs_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='csrequest',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csrequest',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csrequest',
            name='is_shipped',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csrequest',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csrequest',
            name='request_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
