# Generated by Django 3.2.12 on 2023-06-27 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_workdetail_new_draft'),
        ('cs', '0014_auto_20230627_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrequest',
            name='order_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_requests', to='order.ordermaster'),
        ),
    ]
