# Generated by Django 3.2.12 on 2023-06-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0016_auto_20230627_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrequestrefund',
            name='status',
            field=models.CharField(default='반품요청', max_length=10),
        ),
    ]
