# Generated by Django 3.2.12 on 2023-06-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0017_csrequestrefund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmaster',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
