# Generated by Django 3.2.12 on 2023-06-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0019_auto_20230628_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrequest',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
