# Generated by Django 3.2.12 on 2023-06-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0020_alter_csrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrequest',
            name='order_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
