# Generated by Django 3.2.12 on 2023-06-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0021_alter_csrequest_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrequestchange',
            name='status',
            field=models.CharField(default='교환요청', max_length=10),
        ),
    ]
