# Generated by Django 3.2.12 on 2023-06-29 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_workdetail_new_draft'),
        ('cs', '0022_csrequestchange_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsRequestCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_reason', models.CharField(max_length=100, null=True)),
                ('current_smarter_money', models.IntegerField(null=True)),
                ('after_smarter_money', models.IntegerField(null=True)),
                ('memo', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='취소요청', max_length=10)),
                ('cs_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancels', to='cs.csrequest')),
            ],
            options={
                'db_table': 'cs_request_cancels',
            },
        ),
        migrations.CreateModel(
            name='CsRequestCancelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_quantity', models.IntegerField(null=True)),
                ('cancel_price', models.IntegerField(null=True)),
                ('cs_request_cancel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_details', to='cs.csrequestcancel')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancel_details', to='order.orderdetail')),
            ],
            options={
                'db_table': 'cs_request_cancel_details',
            },
        ),
    ]
