# Generated by Django 3.2.12 on 2023-06-29 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_workdetail_new_draft'),
        ('cs', '0023_csrequestcancel_csrequestcanceldetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csrequestcancel',
            old_name='after_smarter_money',
            new_name='total_delivery_price',
        ),
        migrations.RenameField(
            model_name='csrequestcancel',
            old_name='current_smarter_money',
            new_name='total_products_price',
        ),
        migrations.AddField(
            model_name='csrequestcancel',
            name='order_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancels', to='order.ordermaster'),
        ),
        migrations.AddField(
            model_name='csrequestcancel',
            name='total_work_labor_price',
            field=models.IntegerField(null=True),
        ),
    ]
