# Generated by Django 3.2.12 on 2023-06-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0024_auto_20230629_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrequestcancel',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
