# Generated by Django 3.2.12 on 2023-07-03 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20230629_1314'),
        ('cs', '0025_csrequestcancel_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csrequestchange',
            old_name='picked_address',
            new_name='pick_up_address',
        ),
        migrations.RenameField(
            model_name='csrequestchange',
            old_name='picked_detail_address',
            new_name='pick_up_detail_address',
        ),
        migrations.RenameField(
            model_name='csrequestchange',
            old_name='picked_phone',
            new_name='pick_up_phone',
        ),
        migrations.RenameField(
            model_name='csrequestchangedetail',
            old_name='changed_color',
            new_name='changing_color',
        ),
        migrations.RenameField(
            model_name='csrequestchangedetail',
            old_name='changed_quantity',
            new_name='changing_quantity',
        ),
        migrations.RenameField(
            model_name='csrequestchangedetail',
            old_name='changed_size',
            new_name='changing_size',
        ),
        migrations.RemoveField(
            model_name='csrequestchangedetail',
            name='changed_order_detail',
        ),
        migrations.RemoveField(
            model_name='csrequestchangedetail',
            name='old_order_detail',
        ),
        migrations.AddField(
            model_name='csrequestchangedetail',
            name='changed_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changed_products', to='product.product'),
        ),
        migrations.AddField(
            model_name='csrequestchangedetail',
            name='changing_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changing_products', to='product.product'),
        ),
    ]
