# Generated by Django 3.2.12 on 2023-07-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0026_auto_20230703_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csrequestchange',
            old_name='changed_price',
            new_name='changing_products_price',
        ),
        migrations.RenameField(
            model_name='csrequestchange',
            old_name='total_price',
            new_name='payment_amount',
        ),
    ]
