# Generated by Django 3.2.12 on 2023-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0026_auto_20230703_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrequest',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
