# Generated by Django 3.2.12 on 2023-07-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0027_auto_20230703_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrequestchange',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
