# Generated by Django 3.2.12 on 2023-07-04 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_workdetail_new_draft'),
        ('cs', '0027_csrequest_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_request_number', models.CharField(max_length=20)),
                ('order_number', models.CharField(max_length=25)),
                ('gym_name', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('price_products', models.IntegerField()),
                ('price_works', models.IntegerField()),
                ('price_delivery', models.IntegerField()),
                ('price_total', models.IntegerField()),
                ('state', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('cs_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cs.csrequest')),
                ('order_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.ordermaster')),
            ],
            options={
                'db_table': 'cancel_order_requests',
            },
        ),
    ]
