# Generated by Django 3.2.12 on 2023-07-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0028_csrequestchange_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csrequestchangedetail',
            old_name='additional_product_price',
            new_name='changing_price',
        ),
        migrations.RemoveField(
            model_name='csrequestchangedetail',
            name='additional_total_price',
        ),
        migrations.RemoveField(
            model_name='csrequestchangedetail',
            name='changing_color',
        ),
        migrations.RemoveField(
            model_name='csrequestchangedetail',
            name='changing_size',
        ),
    ]
