# Generated by Django 3.2.12 on 2023-07-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0029_auto_20230703_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csrequestchange',
            old_name='picked_receiver',
            new_name='pick_up_receiver',
        ),
    ]
