# Generated by Django 3.2.12 on 2023-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0030_rename_picked_receiver_csrequestchange_pick_up_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrequestchange',
            name='delivered_zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='csrequestchange',
            name='pick_up_zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
