# Generated by Django 3.2.12 on 2023-07-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0028_cancelorderrequest'),
        ('cs', '0032_csrequestchangedetail_delivery'),
    ]

    operations = [
    ]
