# Generated by Django 3.2.12 on 2023-07-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0034_auto_20230704_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csrequestcanceldetail',
            name='cs_request_cancel',
        ),
        migrations.RemoveField(
            model_name='csrequestcanceldetail',
            name='order_detail',
        ),
        migrations.DeleteModel(
            name='CsRequestCancel',
        ),
        migrations.DeleteModel(
            name='CsRequestCancelDetail',
        ),
    ]
