# Generated by Django 3.2.12 on 2023-07-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_workdetail_new_draft'),
        ('cs', '0034_auto_20230704_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cspartialcancelhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='cspartialcancelhistory',
            name='canceled_quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cspartialcancelhistory',
            name='color',
            field=models.CharField(default='red', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cspartialcancelhistory',
            name='cs_request_number',
            field=models.CharField(default='R12314124', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cspartialcancelhistory',
            name='gym_name',
            field=models.CharField(default='gym', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cspartialcancelhistory',
            name='order_number',
            field=models.CharField(default='O125125125', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cspartialcancelhistory',
            name='price_product',
            field=models.IntegerField(default=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cspartialcancelhistory',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cspartialcancelhistory',
            name='size',
            field=models.CharField(default='L', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cspartialcancelhistory',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cs_order_change_histories', to='order.orderdetail'),
        ),
    ]
