# Generated by Django 3.2.12 on 2023-07-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0035_auto_20230704_1533'),
        ('cs', '0035_auto_20230704_1709'),
    ]

    operations = [
    ]
