# Generated by Django 3.2.12 on 2023-07-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0037_cspartialcancelhistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrequestchangedetail',
            name='price_work',
            field=models.IntegerField(default=0),
        ),
    ]
