# Generated by Django 3.2.12 on 2023-07-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0037_cspartialcancelhistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cspartialcancelhistory',
            name='product_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
