# Generated by Django 3.2.12 on 2023-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0038_cspartialcancelhistory_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cspartialcancelhistory',
            name='price_total',
            field=models.IntegerField(default=17000),
            preserve_default=False,
        ),
    ]
