# Generated by Django 3.2.12 on 2023-07-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0038_csrequestchangedetail_price_work'),
        ('cs', '0039_cspartialcancelhistory_price_total'),
    ]

    operations = [
    ]
