# Generated by Django 3.2.12 on 2023-07-05 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0040_merge_20230705_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csrequest',
            name='memo',
        ),
        migrations.CreateModel(
            name='CsRequestMemos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cs_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_memos', to='cs.csrequest')),
            ],
            options={
                'db_table': 'cs_request_memos',
            },
        ),
    ]
