# Generated by Django 3.2.12 on 2023-07-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0041_auto_20230705_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CsRequestChange',
            new_name='ChangeRequest',
        ),
        migrations.AlterModelTable(
            name='changerequest',
            table='change_requests',
        ),
    ]
