# Generated by Django 3.2.12 on 2023-07-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0043_auto_20230705_1426'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='returnrequestdetail',
            table='return_request_details',
        ),
    ]
