# Generated by Django 3.2.12 on 2023-07-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0044_alter_returnrequestdetail_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='after_smarter_money',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='current_smarter_money',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='is_delivery_price_exempt',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='total_products_price',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='total_refund_delivery_price',
        ),
    ]
