# Generated by Django 3.2.12 on 2023-07-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0045_auto_20230705_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnrequest',
            old_name='status',
            new_name='state',
        ),
    ]
