# Generated by Django 3.2.12 on 2023-07-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0047_auto_20230705_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changerequest',
            old_name='status',
            new_name='state',
        ),
    ]
