# Generated by Django 3.2.12 on 2023-07-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0050_rename_changing_products_price_changerequest_total_changing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changerequest',
            old_name='delivered_address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='changerequest',
            old_name='delivered_detail_address',
            new_name='delivery_detail_address',
        ),
        migrations.RenameField(
            model_name='changerequest',
            old_name='delivered_phone',
            new_name='delivery_phone',
        ),
        migrations.RenameField(
            model_name='changerequest',
            old_name='delivered_receiver',
            new_name='delivery_receiver',
        ),
        migrations.RenameField(
            model_name='changerequest',
            old_name='delivered_zip_code',
            new_name='delivery_zip_code',
        ),
    ]
