# Generated by Django 3.2.12 on 2023-07-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0051_auto_20230707_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='price_to_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
