# Generated by Django 3.2.12 on 2023-07-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0052_changerequest_price_to_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequestdetail',
            name='additional_price',
        ),
        migrations.AddField(
            model_name='changerequestdetail',
            name='total_changing_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='changerequestdetail',
            name='changing_price',
            field=models.IntegerField(default=0),
        ),
    ]
