# Generated by Django 3.2.12 on 2023-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0053_auto_20230707_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='after_smarter_money',
            field=models.IntegerField(default=0),
        ),
    ]
