# Generated by Django 3.2.12 on 2023-07-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0054_alter_changerequest_after_smarter_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='after_smarter_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='delivery_price',
            field=models.IntegerField(default=0),
        ),
    ]
