# Generated by Django 3.2.12 on 2023-07-10 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_auto_20230707_1146'),
        ('cs', '0055_auto_20230707_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnrequest',
            old_name='refund_reason',
            new_name='return_reason',
        ),
        migrations.RenameField(
            model_name='returnrequest',
            old_name='total_refund_price',
            new_name='total_return_price',
        ),
        migrations.RenameField(
            model_name='returnrequestdetail',
            old_name='cs_request_refund',
            new_name='cs_request_return',
        ),
        migrations.RenameField(
            model_name='returnrequestdetail',
            old_name='refund_price',
            new_name='return_price',
        ),
        migrations.RenameField(
            model_name='returnrequestdetail',
            old_name='refund_quantity',
            new_name='return_quantity',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change', to='order.delivery'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='cs_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='cs.csrequest'),
        ),
    ]
