# Generated by Django 3.2.12 on 2023-07-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0056_auto_20230710_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='after_smarter_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='current_smarter_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='delivery_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='is_delivery_price_exempt',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='total_products_price',
            field=models.IntegerField(null=True),
        ),
    ]
