# Generated by Django 3.2.12 on 2023-07-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0058_auto_20230710_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequestdetail',
            name='price_work',
            field=models.IntegerField(default=0),
        ),
    ]
