# Generated by Django 3.2.12 on 2023-07-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_remove_gym_cumulative_purchase_amount'),
        ('cs', '0060_auto_20230717_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='nominee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.gym'),
        ),
    ]
