# Generated by Django 3.2.12 on 2023-07-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_alter_addresszipcode_parent'),
        ('business', '0028_remove_gym_cumulative_purchase_amount'),
        ('cs', '0062_auto_20230720_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponMasterIssueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=10, null=True)),
                ('threshold_amount', models.IntegerField(blank=True, null=True)),
                ('issued_count_per_gym', models.IntegerField()),
                ('issued_amount_per_gym', models.IntegerField()),
                ('total_issued_count', models.IntegerField()),
                ('total_issued_amount', models.IntegerField()),
                ('expired_day', models.IntegerField()),
                ('coupon_message', models.TextField()),
                ('coupon_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cs.couponmaster')),
                ('issued_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.addresszipcode')),
                ('issued_gyms', models.ManyToManyField(to='business.Gym')),
            ],
            options={
                'db_table': 'manual_coupon_master_issue_histories',
            },
        ),
    ]
