# Generated by Django 3.2.12 on 2023-07-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0063_couponmasterissuehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmasterissuehistory',
            name='search_type',
            field=models.CharField(default='직접검색', max_length=10),
            preserve_default=False,
        ),
    ]
