# Generated by Django 3.2.12 on 2023-07-20 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0064_couponmasterissuehistory_search_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmasterissuehistory',
            name='date_issued',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
