# Generated by Django 3.2.12 on 2023-07-26 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0065_couponmasterissuehistory_date_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelorderrequest',
            name='is_without_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancelorderrequest',
            name='cs_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cs.csrequest'),
        ),
        migrations.AlterField(
            model_name='cancelorderrequest',
            name='cs_request_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
