# Generated by Django 3.2.12 on 2023-07-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0066_auto_20230726_0936'),
        ('cs', '0066_csrequestcontents_parent'),
    ]

    operations = [
    ]
