# Generated by Django 3.2.12 on 2023-07-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0067_auto_20230726_1047'),
        ('cs', '0067_merge_20230726_1037'),
    ]

    operations = [
    ]
