# Generated by Django 3.2.12 on 2022-10-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lack_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
