# Generated by Django 3.2.12 on 2022-10-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_lack_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaster',
            options={'ordering': ('-date_created',)},
        ),
    ]
