# Generated by Django 3.2.12 on 2022-11-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_lack_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lack_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
