# Generated by Django 3.2.12 on 2022-11-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_lack_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaster',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='product_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
