# Generated by Django 3.2.12 on 2022-11-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20221107_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('date_created',)},
        ),
    ]
