# Generated by Django 3.2.12 on 2022-11-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail'),
        ),
    ]
