# Generated by Django 3.2.12 on 2022-11-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productmaster_description_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail'),
        ),
    ]
