# Generated by Django 3.2.12 on 2022-11-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productmaster_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
