# Generated by Django 3.2.12 on 2022-11-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productmaster_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaster',
            options={'ordering': ('date_created',)},
        ),
    ]
