# Generated by Django 3.2.12 on 2022-11-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productmaster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='font',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='thread_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
