# Generated by Django 3.2.12 on 2022-11-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_draft_draft_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftrequest',
            name='draft',
        ),
    ]
