# Generated by Django 3.2.12 on 2022-11-25 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_draftrequest_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='default_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.draft'),
        ),
    ]
