# Generated by Django 3.2.12 on 2023-03-31 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productmaster_default_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='member/logo')),
            ],
        ),
        migrations.AddField(
            model_name='draft',
            name='draft_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.draftimage'),
        ),
    ]
