# Generated by Django 3.2.12 on 2023-06-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20230623_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdraft',
            name='font',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newdraft',
            name='thread_color',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
