# Generated by Django 3.2.12 on 2023-06-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20230623_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdraft',
            name='back_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='back_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='flag_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='flag_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='heap_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='heap_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='left_chest_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='left_chest_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='left_pant_low_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='left_pant_low_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='left_pant_middle_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='left_pant_middle_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='left_shoulder_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='left_shoulder_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='right_chest_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='right_chest_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='right_pant_low_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='right_pant_low_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='right_pant_middle_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='right_pant_middle_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='right_shoulder_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdraft',
            name='right_shoulder_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
