# Generated by Django 3.2.12 on 2023-07-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_productmaster_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaster',
            options={'ordering': ('display_order',)},
        ),
    ]
