# Generated by Django 3.2.12 on 2023-07-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_productmaster_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaster',
            options={'ordering': ('category_id', 'display_order')},
        ),
    ]
