# Generated by Django 3.2.12 on 2023-07-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_productmaster_memo'),
        ('product', '0033_alter_productmaster_options'),
    ]

    operations = [
    ]
