# Generated by Django 3.2.12 on 2023-07-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_merge_20230713_1500'),
        ('product', '0034_merge_20230713_1516'),
    ]

    operations = [
    ]
