# Generated by Django 3.2.12 on 2023-07-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_merge_20230713_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaster',
            options={'ordering': ('display_order',)},
        ),
        migrations.RemoveField(
            model_name='draftrequest',
            name='product_master',
        ),
    ]
