# Generated by Django 3.2.12 on 2023-07-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20230723_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdraft',
            name='back_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='back_width',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='flag_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='flag_width',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='heap_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='heap_width',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='left_chest_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='left_chest_width',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='left_pant_low_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='left_pant_low_width',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='left_pant_middle_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='left_pant_middle_width',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='left_shoulder_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='left_shoulder_width',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='right_chest_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='right_chest_width',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='right_pant_low_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='right_pant_low_width',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='right_pant_middle_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='right_pant_middle_width',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='right_shoulder_height',
        ),
        migrations.RemoveField(
            model_name='newdraft',
            name='right_shoulder_width',
        ),
    ]
