# Generated by Django 3.2.12 on 2022-10-21 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=20)),
                ('installmentPlanMonths', models.IntegerField()),
                ('approveNo', models.CharField(max_length=10)),
                ('cardType', models.CharField(max_length=10)),
                ('ownerType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('orderId', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payBy', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('orderId', models.CharField(max_length=64)),
                ('orderName', models.CharField(max_length=100)),
                ('customerName', models.CharField(max_length=30)),
                ('requestedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=20)),
                ('settlementStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mId', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('requestedAt', models.DateTimeField()),
                ('approvedAt', models.DateTimeField()),
                ('country', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('totalAmount', models.IntegerField()),
                ('balanceAmount', models.IntegerField()),
                ('suppliedAmount', models.IntegerField()),
                ('vat', models.IntegerField()),
                ('texFreeAmount', models.IntegerField()),
                ('method', models.CharField(max_length=20)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_success', to='payment.cardsuccess')),
                ('transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_success', to='payment.transfersuccess')),
            ],
        ),
    ]
