# Generated by Django 3.2.12 on 2022-10-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsuccess',
            name='card',
        ),
        migrations.RemoveField(
            model_name='paymentsuccess',
            name='transfer',
        ),
    ]
