# Generated by Django 3.2.12 on 2022-10-21 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentsuccess_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsuccess',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='orderId',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='paymentKey',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_success', to='payment.transfersuccess'),
        ),
    ]
