# Generated by Django 3.2.12 on 2022-10-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20221021_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='payBy',
            new_name='method',
        ),
    ]
