# Generated by Django 3.2.12 on 2023-05-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_paymentrequest_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelsuccess',
            name='receiptKey',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
