# Generated by Django 3.2.12 on 2022-11-29 06:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0021_auto_20221123_2219'),
        #('gym_class', '0002_initial'),
        #('gym_student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('contents', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('class_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gym_notifications', to='gym_class.classmaster')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gym_notifications', to='business.gym')),
            ],
        ),
        migrations.CreateModel(
            name='GymNotificationReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('gym_notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivers', to='notification.gymnotification')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receivers', to='gym_student.parent')),
            ],
        ),
    ]
