# Generated by Django 3.2.12 on 2022-12-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_gymnotification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymnotification',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
