# Generated by Django 3.2.12 on 2022-12-20 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0027_auto_20221215_1351'),
        ('notification', '0002_alter_gymnotification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnotification',
            name='class_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gym_notifications', to='gym_class.classmaster'),
        ),
    ]
