# Generated by Django 3.2.12 on 2022-12-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_gymnotification_class_master'),
        ('notification', '0003_rename_date_create_gymnotification_date_created'),
    ]

    operations = [
    ]
