# Generated by Django 3.2.12 on 2023-04-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_gymnotification_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnotification',
            name='contents',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='gymnotification',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
