# Generated by Django 3.2.12 on 2023-04-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_alter_gymnotificationreceiver_gym_notification'),
        ('notification', '0008_auto_20230427_1436'),
    ]

    operations = [
    ]
