# Generated by Django 3.2.12 on 2022-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagency',
            name='cargo_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagency',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagency',
            name='is_default',
            field=models.BooleanField(null=True),
        ),
    ]
