# Generated by Django 3.2.12 on 2022-10-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
