# Generated by Django 3.2.12 on 2022-10-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_infobankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infobankaccount',
            name='name',
        ),
        migrations.AlterField(
            model_name='infobankaccount',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='infobankaccount',
            name='is_default',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
