# Generated by Django 3.2.12 on 2022-10-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20221028_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_information', models.CharField(max_length=100)),
                ('basic', models.BooleanField(default=False)),
                ('is_use', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(max_length=20)),
                ('condition', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
        ),
    ]
