# Generated by Django 3.2.12 on 2022-10-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_infodelivery_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership',
            new_name='name',
        ),
    ]
