# Generated by Django 3.2.12 on 2022-10-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_rename_membership_membership_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
