# Generated by Django 3.2.12 on 2022-10-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_membership_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
