# Generated by Django 3.2.12 on 2022-10-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_deliveryagency_cargo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobankaccount',
            name='owner_name',
            field=models.CharField(default='주식회사 스마터', max_length=10),
            preserve_default=False,
        ),
    ]
