# Generated by Django 3.2.12 on 2022-10-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_infobankaccount_owner_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoDelivery',
        ),
    ]
