# Generated by Django 3.2.12 on 2022-10-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_rename_infobankaccount_bankaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('id',)},
        ),
    ]
