# Generated by Django 3.2.12 on 2022-10-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_bankaccount_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPriceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=3000)),
            ],
        ),
    ]
