# Generated by Django 3.2.12 on 2022-10-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_extrapricedelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('order',)},
        ),
    ]
