# Generated by Django 3.2.12 on 2022-11-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20221101_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='content',
        ),
        migrations.AddField(
            model_name='notice',
            name='contents',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
