# Generated by Django 3.2.12 on 2022-11-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20221101_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
