# Generated by Django 3.2.12 on 2022-11-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_alter_notice_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='contents',
            field=models.CharField(max_length=255),
        ),
    ]
