# Generated by Django 3.2.12 on 2022-11-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20221108_1035'),
        ('common', '0026_auto_20221108_1502'),
    ]

    operations = [
    ]
