# Generated by Django 3.2.12 on 2022-11-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_merge_0026_auto_20221108_1035_0026_auto_20221108_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='contents',
            field=models.TextField(),
        ),
    ]
