# Generated by Django 3.2.12 on 2022-12-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_rename_address_detail_address_detail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
