# Generated by Django 3.2.12 on 2023-06-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delivery_memo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
