# Generated by Django 3.2.12 on 2023-07-19 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_address_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('si_do', models.CharField(max_length=10)),
                ('si_gun_gu', models.CharField(max_length=20, null=True)),
                ('zip_code_start', models.CharField(max_length=5)),
                ('zip_code_end', models.CharField(max_length=5)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.addresszipcode')),
            ],
        ),
    ]
