# Generated by Django 3.2.12 on 2023-07-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_addresszipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresszipcode',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.addresszipcode'),
        ),
    ]
