# Generated by Django 3.2.12 on 2023-07-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_alter_addresszipcode_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresszipcode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.addresszipcode'),
        ),
        migrations.AlterField(
            model_name='addresszipcode',
            name='si_gun_gu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
