# Generated by Django 3.2.12 on 2023-07-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_auto_20230719_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresszipcode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.addresszipcode'),
        ),
    ]
