# Generated by Django 3.2.12 on 2022-11-29 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0021_auto_20221123_2219'),
        ('product', '0022_productmaster_default_draft'),
        ('gym_class', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('detail_address', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=15)),
                ('supporter_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('date_entered', models.DateField()),
                ('day_to_pay', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('class_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='gym_class.classmaster')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='gym_class.level')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='gym_student.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='gym_student.school')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parents', to='gym_student.relationship'),
        ),
        migrations.AddField(
            model_name='parent',
            name='supporter_relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supporter_parents', to='gym_student.relationship'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_audition', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audition_masters_current', to='gym_class.level')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audition_masters', to='business.gym')),
                ('next_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audition_masters_next', to='gym_class.level')),
            ],
        ),
        migrations.CreateModel(
            name='AuditionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_pass', models.BooleanField()),
                ('audition_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audition_details', to='gym_student.auditionmaster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audition_details', to='gym_student.student')),
            ],
        ),
    ]
