# Generated by Django 3.2.12 on 2022-11-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0001_initial'),
    ]

    operations = [

    ]
