# Generated by Django 3.2.12 on 2022-12-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0002_auto_20221129_1545'),
    ]

    operations = [
    ]
