# Generated by Django 3.2.12 on 2022-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0003_auto_20221130_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditionmaster',
            name='date_audition',
            field=models.DateField(),
        ),
    ]
