# Generated by Django 3.2.12 on 2022-12-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0003_merge_0002_auto_20221129_1545_0002_auto_20221201_1540'),
        ('gym_student', '0004_alter_auditionmaster_date_audition'),
    ]

    operations = [
    ]
