# Generated by Django 3.2.12 on 2022-12-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0005_merge_20221202_1042'),
    ]

    operations = [

    ]
