# Generated by Django 3.2.12 on 2022-12-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0007_auto_20221208_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
