# Generated by Django 3.2.12 on 2022-12-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0013_gymalarm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymAlarm',
        ),
    ]
