# Generated by Django 3.2.12 on 2022-12-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0014_delete_gymalarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='detail_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
