# Generated by Django 3.2.12 on 2023-02-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0015_auto_20221229_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='memo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='memo_for_health',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='memo_for_price',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='price_to_pay',
            field=models.IntegerField(null=True),
        ),
    ]
