# Generated by Django 3.2.12 on 2023-02-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0017_alter_student_price_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditiondetail',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
