# Generated by Django 3.2.12 on 2023-02-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0018_auditiondetail_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditionmaster',
            name='estimated_alarm_date',
            field=models.DateField(null=True),
        ),
    ]
