# Generated by Django 3.2.12 on 2023-03-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0021_alter_auditionmaster_estimated_alarm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
