# Generated by Django 3.2.12 on 2022-11-29 06:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0021_auto_20221123_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('absent_reason', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_absent', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('belt', models.CharField(max_length=20)),
                ('poomsae', models.CharField(max_length=15)),
                ('order', models.IntegerField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='business.gym')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),

                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_masters', to='business.gym')),
            ],
        ),
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('class_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_details', to='gym_class.classmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=15)),
                ('date_attended', models.DateTimeField()),
                ('absent_reason', models.CharField(max_length=200, null=True)),
                ('class_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gym_class.classdetail')),
                ('class_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='gym_class.classmaster')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='business.gym')),

            ],
        ),

    ]
