# Generated by Django 3.2.12 on 2022-11-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetail',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classdetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classmaster',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classmaster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
