# Generated by Django 3.2.12 on 2022-11-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0003_auto_20221129_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
