# Generated by Django 3.2.12 on 2022-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0004_alter_classmaster_price_deduct_per_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmaster',
            name='date_deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
