# Generated by Django 3.2.12 on 2022-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0006_remove_classdetail_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
