# Generated by Django 3.2.12 on 2022-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0007_classdetail_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetail',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='classdetail',
            name='time_start',
        ),
        migrations.AddField(
            model_name='classdetail',
            name='hour_end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classdetail',
            name='hour_start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classdetail',
            name='min_end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classdetail',
            name='min_start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
