# Generated by Django 3.2.12 on 2022-12-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0009_remove_classmaster_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmaster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
