# Generated by Django 3.2.12 on 2022-12-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0010_classmaster_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmaster',
            name='date_deleted',
        ),
    ]
