# Generated by Django 3.2.12 on 2022-12-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0012_classmaster_date_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetail',
            name='date_deleted',
        ),
    ]
