# Generated by Django 3.2.12 on 2022-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0013_remove_classdetail_date_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetail',
            name='date_deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
