# Generated by Django 3.2.12 on 2022-12-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0004_auto_20221130_1605'),
        ('gym_class', '0014_classdetail_date_deleted'),
    ]

    operations = [
    ]
