# Generated by Django 3.2.12 on 2022-12-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0015_merge_20221202_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentrequest',
            name='memo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='classdetail',
            name='date_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='classmaster',
            name='date_deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
