# Generated by Django 3.2.12 on 2022-12-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0016_auto_20221206_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absentrequest',
            name='date_absent',
        ),
    ]
