# Generated by Django 3.2.12 on 2022-12-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0016_auto_20221202_1427'),
        ('gym_class', '0019_alter_absentrequest_date_absent'),
    ]

    operations = [
    ]
