# Generated by Django 3.2.12 on 2022-12-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0020_merge_20221207_2227'),
        ('gym_class', '0020_merge_20221208_1321'),
    ]

    operations = [
    ]
