# Generated by Django 3.2.12 on 2022-12-14 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_student', '0009_auto_20221209_1333'),
        ('business', '0022_gym_is_deduct_enabled'),
        ('gym_class', '0021_merge_20221209_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('date_attended', models.DateTimeField(blank=True, null=True)),
                ('absent_reason', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('class_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gym_class.classdetail')),
                ('class_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='gym_class.classmaster')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AddField(
            model_name='attendancedetail',
            name='attendance_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_details', to='gym_class.attendancemaster'),
        ),
        migrations.AddField(
            model_name='attendancedetail',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_details', to='business.gym'),
        ),
        migrations.AddField(
            model_name='attendancedetail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_details', to='gym_student.student'),
        ),
    ]
