# Generated by Django 3.2.12 on 2022-12-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0025_alter_attendancemaster_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentrequest',
            name='absent_reason',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
