# Generated by Django 3.2.12 on 2022-12-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0026_alter_absentrequest_absent_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentrequest',
            name='absent_reason',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='attendancedetail',
            name='absent_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
