# Generated by Django 3.2.12 on 2022-12-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0027_auto_20221215_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absentrequest',
            name='memo',
        ),
    ]
