# Generated by Django 3.2.12 on 2022-12-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0028_remove_absentrequest_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentrequest',
            name='date_absent',
            field=models.DateTimeField(),
        ),
    ]
