# Generated by Django 3.2.12 on 2023-02-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0029_alter_absentrequest_date_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmaster',
            name='price',
        ),
        migrations.RemoveField(
            model_name='classmaster',
            name='price_deduct_per_absent',
        ),
    ]
