# Generated by Django 3.2.12 on 2023-02-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0030_auto_20230214_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='poomsae',
        ),
        migrations.AddField(
            model_name='level',
            name='belt_brand',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='belt_color',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
