# Generated by Django 3.2.12 on 2023-03-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0031_auto_20230223_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedetail',
            name='date_attended',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
