# Generated by Django 3.2.12 on 2023-03-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0032_alter_attendancedetail_date_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemaster',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
