# Generated by Django 3.2.12 on 2023-04-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_class', '0033_alter_attendancemaster_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedetail',
            name='date_attended',
            field=models.DateTimeField(null=True),
        ),
    ]
