# Generated by Django 3.2.12 on 2022-10-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmarterMoneyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_number', models.CharField(max_length=15)),
                ('order_number', models.CharField(max_length=15, null=True)),
                ('history_type', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('order_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smarter_money_history', to='order.ordermaster')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='smarter_money.wallet')),
            ],
        ),
    ]
