# Generated by Django 3.2.12 on 2022-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarter_money', '0002_auto_20221021_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartermoneyhistory',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
