# Generated by Django 3.2.12 on 2022-10-23 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smarter_money', '0003_smartermoneyhistory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=15, unique=True)),
                ('amount', models.IntegerField()),
                ('method', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
