# Generated by Django 3.2.12 on 2022-10-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarter_money', '0006_auto_20221023_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartermoneyhistory',
            name='history_number',
            field=models.CharField(max_length=25),
        ),
    ]
