# Generated by Django 3.2.12 on 2022-10-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarter_money', '0007_alter_smartermoneyhistory_history_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargerequest',
            name='id',
        ),
        migrations.AlterField(
            model_name='chargerequest',
            name='order_id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
