# Generated by Django 3.2.12 on 2022-10-23 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smarter_money', '0008_auto_20221023_0838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChargeRequest',
            new_name='ChargeOrder',
        ),
    ]
