# Generated by Django 3.2.12 on 2022-11-21 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_auto_20221121_1529'),
        ('smarter_money', '0012_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartermoneyhistory',
            name='order_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smarter_money_history', to='order.ordermaster'),
        ),
    ]
