# Generated by Django 3.2.12 on 2022-11-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarter_money', '0013_alter_smartermoneyhistory_order_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeorder',
            name='order_name',
            field=models.CharField(max_length=10),
        ),
    ]
