# Generated by Django 3.2.12 on 2023-01-04 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_alter_orderdetail_work'),
        ('smarter_money', '0014_alter_chargeorder_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartermoneyhistory',
            name='order_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smarter_money_history', to='order.ordermaster'),
        ),
        migrations.AlterField(
            model_name='smartermoneyhistory',
            name='order_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
