# Generated by Django 3.2.12 on 2023-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0099_ordermaster_coupon'),
        ('smarter_money', '0016_smarterpaidhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smarterpaidhistory',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='smarterpaidhistory',
            name='order_detail',
            field=models.ManyToManyField(blank=True, null=True, related_name='smarter_paid_histories', to='order.OrderDetail'),
        ),
    ]
