# Generated by Django 3.2.12 on 2023-07-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarter_money', '0017_auto_20230725_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smarterpaidhistory',
            old_name='order_detail',
            new_name='order_details',
        ),
    ]
