# Generated by Django 3.2.12 on 2023-08-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0100_alter_orderdetail_new_draft'),
        ('smarter_money', '0018_rename_order_detail_smarterpaidhistory_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smarterpaidhistory',
            name='order_details',
            field=models.ManyToManyField(blank=True, related_name='smarter_paid_histories', to='order.OrderDetail'),
        ),
    ]
