# Generated by Django 3.2.12 on 2022-10-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='detail_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
