# Generated by Django 3.2.12 on 2022-10-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20221024_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='manager',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
