# Generated by Django 3.2.12 on 2022-10-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20221025_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorderdetail',
            name='price_vendor_total',
            field=models.IntegerField(),
        ),
    ]
