# Generated by Django 3.2.12 on 2022-10-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryorderdetail_price_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryorderdetail',
            name='price_total',
        ),
    ]
