# Generated by Django 3.2.12 on 2022-10-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_inventoryorderdetail_price_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryordermaster',
            name='price_total',
            field=models.IntegerField(null=True),
        ),
    ]
