# Generated by Django 3.2.12 on 2022-10-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventoryordermaster_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorderdetail',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryorderdetail',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryorderdetail',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
