# Generated by Django 3.2.12 on 2022-10-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20221025_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorderdetail',
            name='color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryorderdetail',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryorderdetail',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
