# Generated by Django 3.2.12 on 2022-10-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventoryreceiveddetail_inventoryreceivedmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceiveddetail',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreceiveddetail',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreceiveddetail',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
