# Generated by Django 3.2.12 on 2022-10-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20221026_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changehistory',
            options={'ordering': ('-date_created',)},
        ),
    ]
