# Generated by Django 3.2.12 on 2022-10-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_changehistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorderdetail',
            name='inventory_order_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.inventoryordermaster'),
        ),
    ]
