# Generated by Django 3.2.12 on 2022-10-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_inventoryorderdetail_inventory_order_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryordermaster',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
