# Generated by Django 3.2.12 on 2022-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_inventoryordermaster_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceiveddetail',
            name='expected_inventory_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryreceiveddetail',
            name='goal_inventory_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryreceiveddetail',
            name='inventory_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
