# Generated by Django 3.2.12 on 2022-10-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20221026_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreceiveddetail',
            name='expected_inventory_quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryreceiveddetail',
            name='goal_inventory_quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryreceiveddetail',
            name='inventory_quantity',
        ),
        migrations.AddField(
            model_name='inventoryorderdetail',
            name='expected_inventory_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryorderdetail',
            name='goal_inventory_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryorderdetail',
            name='inventory_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
