# Generated by Django 3.2.12 on 2022-10-27 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_inventoryordermaster_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryreceiveddetail',
            old_name='price_vendor_total',
            new_name='price_ordered',
        ),
        migrations.RenameField(
            model_name='inventoryreceiveddetail',
            old_name='received_price_total',
            new_name='price_received',
        ),
        migrations.RenameField(
            model_name='inventoryreceivedmaster',
            old_name='date_receiving',
            new_name='date_received',
        ),
        migrations.RemoveField(
            model_name='inventoryreceivedmaster',
            name='ordered_price_total',
        ),
        migrations.RemoveField(
            model_name='inventoryreceivedmaster',
            name='quantity_not_received_total',
        ),
        migrations.RemoveField(
            model_name='inventoryreceivedmaster',
            name='quantity_ordered_total',
        ),
        migrations.RemoveField(
            model_name='inventoryreceivedmaster',
            name='quantity_received_total',
        ),
        migrations.RemoveField(
            model_name='inventoryreceivedmaster',
            name='received_price_total',
        ),
        migrations.RemoveField(
            model_name='inventoryreceivedmaster',
            name='receiving_number',
        ),
        migrations.AlterField(
            model_name='inventoryreceiveddetail',
            name='inventory_order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.inventoryorderdetail'),
        ),
    ]
