# Generated by Django 3.2.12 on 2022-10-27 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20221027_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceiveddetail',
            name='inventory_received_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.inventoryreceivedmaster'),
        ),
        migrations.AlterField(
            model_name='inventoryreceiveddetail',
            name='inventory_order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_received', to='inventory.inventoryorderdetail'),
        ),
    ]
