# Generated by Django 3.2.12 on 2022-10-27 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20221027_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreceiveddetail',
            name='inventory_received_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.inventoryreceivedmaster'),
        ),
    ]
