# Generated by Django 3.2.12 on 2022-10-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_inventoryreceiveddetail_inventory_received_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryorderdetail',
            name='quantity_received',
        ),
        migrations.AddField(
            model_name='inventoryorderdetail',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
