# Generated by Django 3.2.12 on 2022-10-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20221027_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryordermaster',
            name='price_total',
        ),
        migrations.RemoveField(
            model_name='inventoryreceivedmaster',
            name='date_ordered',
        ),
    ]
