# Generated by Django 3.2.12 on 2022-10-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20221027_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryreceivedmaster',
            old_name='date_received',
            new_name='date_created',
        ),
    ]
