# Generated by Django 3.2.12 on 2022-10-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_auto_20221028_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='detail_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
