# Generated by Django 3.2.12 on 2022-11-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_inventoryreceiveddetail_quantity_additioanl_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceiveddetail',
            name='price_additional_received',
            field=models.IntegerField(null=True),
        ),
    ]
