# Generated by Django 3.2.12 on 2022-11-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_inventoryreceiveddetail_price_additional_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryreceiveddetail',
            old_name='quantity_additioanl_received',
            new_name='quantity_additional_received',
        ),
    ]
