# Generated by Django 3.2.12 on 2022-11-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_rename_quantity_additioanl_received_inventoryreceiveddetail_quantity_additional_received'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryreceiveddetail',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='inventoryreceivedmaster',
            options={'ordering': ('-id',)},
        ),
    ]
