# Generated by Django 3.2.12 on 2022-11-21 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_auto_20221121_1529'),
        ('inventory', '0040_auto_20221101_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changehistory',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderdetail'),
        ),
    ]
