# Generated by Django 3.2.12 on 2022-11-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_changehistory_order_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
