# Generated by Django 3.2.12 on 2022-12-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_alter_inventoryorderdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorderdetail',
            name='expected_inventory_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryorderdetail',
            name='goal_inventory_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
