# Generated by Django 3.2.12 on 2023-08-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_alter_supplier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
