# Generated by Django 3.2.12 on 2023-04-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_fcm_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_for_password',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='code_limit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
