# Generated by Django 3.2.12 on 2023-08-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_participated_event',
            field=models.BooleanField(default=False),
        ),
    ]
