# Generated by Django 3.2.12 on 2022-10-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='detail_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='detail_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='detail_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='detail_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
