# Generated by Django 3.2.12 on 2022-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='daily_cumulative_work',
            field=models.IntegerField(default=0),
        ),
    ]
