# Generated by Django 3.2.12 on 2022-10-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20221023_1425'),
        ('business', '0002_subcontractor_daily_cumulative_work'),
    ]

    operations = [
    ]
