# Generated by Django 3.2.12 on 2022-10-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_merge_20221023_1554'),
        ('business', '0003_merge_20221024_0440'),
    ]

    operations = [
    ]
