# Generated by Django 3.2.12 on 2022-10-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_merge_20221024_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='membership',
            field=models.CharField(default='일반회원', max_length=10),
        ),
    ]
