# Generated by Django 3.2.12 on 2022-10-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_gym_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='cumulative_purchase_amount',
            field=models.IntegerField(default=0),
        ),
    ]
