# Generated by Django 3.2.12 on 2022-10-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_gym_cumulative_purchase_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='gym',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.agency'),
        ),
    ]
