# Generated by Django 3.2.12 on 2022-10-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20221028_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='is_pre_working',
            field=models.BooleanField(default=False),
        ),
    ]
