# Generated by Django 3.2.12 on 2022-10-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20221028_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractor',
            name='daily_cumulative_work',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
