# Generated by Django 3.2.12 on 2022-10-28 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0010_alter_subcontractor_daily_cumulative_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor', to=settings.AUTH_USER_MODEL),
        ),
    ]
