# Generated by Django 3.2.12 on 2022-10-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_subcontractor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcontractor',
            options={'ordering': ('id',)},
        ),
    ]
