# Generated by Django 3.2.12 on 2022-11-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_subcontractor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gyms', to='business.agency'),
        ),
    ]
