# Generated by Django 3.2.12 on 2022-11-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_gym_agency'),
        ('business', '0014_auto_20221103_0349'),
    ]

    operations = [
    ]
