# Generated by Django 3.2.12 on 2022-11-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_merge_0013_alter_gym_agency_0014_auto_20221103_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='manager_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gym',
            name='owner_name',
            field=models.CharField(max_length=10),
        ),
    ]
