# Generated by Django 3.2.12 on 2022-11-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_alter_agency_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='membership',
        ),
    ]
