# Generated by Django 3.2.12 on 2022-11-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20221123_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gyms', to='business.agency'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='manager_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='owner_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
