# Generated by Django 3.2.12 on 2022-11-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_auto_20221123_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='is_deduct_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
