# Generated by Django 3.2.12 on 2022-12-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_gym_is_deduct_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='bank_account_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='bank_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='bank_owner_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
