# Generated by Django 3.2.12 on 2023-07-07 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0023_auto_20221219_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ta_firm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ta_firms',
            },
        ),
    ]
