# Generated by Django 3.2.12 on 2023-07-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_gymmonthlypurchasedamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='total_purchased_amount',
            field=models.IntegerField(default=0),
        ),
    ]
