# Generated by Django 3.2.12 on 2023-07-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_alter_gymmonthlypurchasedamount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='cumulative_purchase_amount',
        ),
    ]
