# Generated by Django 3.2.12 on 2023-07-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_remove_gym_cumulative_purchase_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='bank_account_no',
            new_name='class_payment_bank_account_no',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='bank_name',
            new_name='class_payment_bank_name',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='bank_owner_name',
            new_name='class_payment_bank_owner_name',
        ),
        migrations.AddField(
            model_name='gym',
            name='refund_bank_account_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='refund_bank_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='refund_bank_owner_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
