# Generated by Django 3.2.12 on 2022-10-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderdetail_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='state',
        ),
    ]
