# Generated by Django 3.2.12 on 2022-10-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderdetail_draft'),
    ]

    operations = [

    ]
