# Generated by Django 3.2.12 on 2022-10-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20221021_1100'),
        ('order', '0005_remove_ordermaster_gym'),
    ]

    operations = [
    ]
