# Generated by Django 3.2.12 on 2022-10-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_merge_20221023_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermaster',
            old_name='address_detail',
            new_name='detail_address',
        ),

        migrations.AddField(
            model_name='orderdetail',
            name='user_request',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
