# Generated by Django 3.2.12 on 2022-10-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_merge_20221024_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),

    ]
