# Generated by Django 3.2.12 on 2022-10-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20221024_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='price_products',
            new_name='price_product',
        ),
    ]
