# Generated by Django 3.2.12 on 2022-10-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20221024_0451'),
        ('order', '0010_rename_price_product_orderdetail_price_products'),
    ]

    operations = [
    ]
