# Generated by Django 3.2.12 on 2022-10-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_merge_20221024_0717'),
    ]

    operations = [

    ]
