# Generated by Django 3.2.12 on 2022-10-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderdetail_price_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='delivery_request',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
