# Generated by Django 3.2.12 on 2022-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_ordermaster_delivery_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='used_smarter_money_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
