# Generated by Django 3.2.12 on 2022-10-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20221024_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='order_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
