# Generated by Django 3.2.12 on 2022-10-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_ordermaster_gym'),
        ('order', '0014_alter_ordermaster_order_number'),
    ]

    operations = [
    ]
