# Generated by Django 3.2.12 on 2022-10-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_merge_20221024_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='used_smarter_money_amount',
        ),
    ]
