# Generated by Django 3.2.12 on 2022-10-25 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_merge_20221024_0717'),
        ('order', '0016_auto_20221024_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermaster',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.gym'),
        ),
        migrations.AlterField(
            model_name='work',
            name='belt_center_letter',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='belt_left_letter',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='belt_right_letter',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
