# Generated by Django 3.2.12 on 2022-10-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20221025_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='work',
            name='belt_center_letter',
        ),
        migrations.RemoveField(
            model_name='work',
            name='belt_left_letter',
        ),
        migrations.RemoveField(
            model_name='work',
            name='belt_right_letter',
        ),
    ]
