# Generated by Django 3.2.12 on 2022-10-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20221020_0420'),
        ('order', '0020_auto_20221025_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='draft_image',
        ),
        migrations.AddField(
            model_name='work',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.draft'),
        ),
    ]
