# Generated by Django 3.2.12 on 2022-10-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20221025_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='draft',
        ),
    ]
