# Generated by Django 3.2.12 on 2022-10-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_remove_work_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='memo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
