# Generated by Django 3.2.12 on 2022-10-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20221025_1309'),
        ('order', '0023_work_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='delivery_agency',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='tracking_number',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('delivery_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.deliveryagency')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='order.delivery'),
        ),
    ]
