# Generated by Django 3.2.12 on 2022-10-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20221025_1423'),
    ]

    operations = [

    ]
