# Generated by Django 3.2.12 on 2022-10-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20221026_0818'),
        ('order', '0025_rename_order_easyorder_order_master'),
    ]

    operations = [
    ]
