# Generated by Django 3.2.12 on 2022-10-26 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_merge_20221026_0858'),
    ]

    operations = [

        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_total', models.IntegerField()),
                ('price_products', models.IntegerField()),
                ('price_total_work', models.IntegerField()),
                ('price_total_work_labor', models.IntegerField()),
                ('state', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='order.orderdetail')),
            ],
        ),
    ]
