# Generated by Django 3.2.12 on 2022-10-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20221026_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ('-date_created',)},
        ),
    ]
