# Generated by Django 3.2.12 on 2022-10-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_alter_claim_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easyorder',
            name='title',
        ),
    ]
