# Generated by Django 3.2.12 on 2022-10-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_remove_easyorder_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyorder',
            name='draft',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='easyorder',
            name='contents',
            field=models.CharField(max_length=255),
        ),

    ]
