# Generated by Django 3.2.12 on 2022-10-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_auto_20221027_0416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EasyOrder',
        ),
    ]
