# Generated by Django 3.2.12 on 2022-10-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_easyorder_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyorder',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
