# Generated by Django 3.2.12 on 2022-10-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_easyorder_date_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='easyorder',
            options={'ordering': ('-date_created',)},
        ),
    ]
