# Generated by Django 3.2.12 on 2022-10-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_rename_cost_zipcode_additional_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.ordermaster'),
        ),
    ]
