# Generated by Django 3.2.12 on 2022-11-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_alter_payment_order_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='refund_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price_consumer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price_gym',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price_parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price_vendor',
            field=models.IntegerField(null=True),
        ),
    ]
