# Generated by Django 3.2.12 on 2022-10-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_alter_payment_order_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyorder',
            name='draft',
            field=models.ImageField(null=True, upload_to='member/logo/request'),
        ),
    ]
