
# Generated by Django 3.2.12 on 2022-11-02 05:50


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_auto_20221101_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='subcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work', to='business.subcontractor'),
        ),
    ]
