# Generated by Django 3.2.12 on 2022-11-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_auto_20221101_0726'),
        ('order', '0041_alter_work_subcontractor'),
    ]

    operations = [
    ]
