# Generated by Django 3.2.12 on 2022-11-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_alter_easyorder_draft'),
        ('order', '0042_merge_20221101_0841'),
    ]

    operations = [
    ]
