# Generated by Django 3.2.12 on 2022-11-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_alter_agency_user'),
        ('order', '0043_merge_20221103_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='subcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to='business.subcontractor'),
        ),
    ]
