# Generated by Django 3.2.12 on 2022-11-04 03:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_alter_work_subcontractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='student_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, default=list, size=None),
        ),
    ]
