# Generated by Django 3.2.12 on 2022-11-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_alter_orderdetail_student_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price_gym',
        ),
    ]
