# Generated by Django 3.2.12 on 2022-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20221108_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
