# Generated by Django 3.2.12 on 2022-11-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_auto_20221108_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price_gym',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price_consumer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price_parent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price_vendor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
