# Generated by Django 3.2.12 on 2022-11-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_auto_20221109_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermaster',
            options={'ordering': ['date_created']},
        ),
    ]
