# Generated by Django 3.2.12 on 2022-11-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_auto_20221109_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
