# Generated by Django 3.2.12 on 2022-11-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_alter_delivery_photo'),
        ('order', '0051_alter_ordermaster_options'),
    ]

    operations = [
    ]
