# Generated by Django 3.2.12 on 2022-11-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_merge_20221114_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
