# Generated by Django 3.2.12 on 2022-11-15 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productmaster_options'),
        ('order', '0052_merge_20221114_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='order.work'),
        ),
        migrations.AddField(
            model_name='work',
            name='draft',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='work',
            name='order_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.ordermaster'),
        ),
        migrations.AddField(
            model_name='work',
            name='product_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to='product.productmaster'),
        ),
    ]
