# Generated by Django 3.2.12 on 2022-11-15 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_ordermaster_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easyorder',
            name='draft',
        ),
        migrations.CreateModel(
            name='EasyOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='member/logo/request')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('easy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.easyorder')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
