# Generated by Django 3.2.12 on 2022-11-15 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productmaster_options'),
        ('order', '0053_auto_20221115_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='work',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.PROTECT, related_name='details', to='order.work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='order_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.ordermaster'),
        ),
        migrations.AlterField(
            model_name='work',
            name='product_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='product.productmaster'),
        ),
    ]
