# Generated by Django 3.2.12 on 2022-11-15 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_auto_20221115_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='order.work'),
        ),
    ]
