# Generated by Django 3.2.12 on 2022-11-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0058_auto_20221115_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_details', to='order.orderdetail')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_details', to='order.work')),
            ],
        ),
    ]
