# Generated by Django 3.2.12 on 2022-11-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productmaster_options'),
        ('order', '0059_workdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='work',
            name='product_master',
        ),
        migrations.AddField(
            model_name='workdetail',
            name='draft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to='product.draft'),
        ),
    ]
