# Generated by Django 3.2.12 on 2022-11-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_auto_20221115_1516'),
        ('order', '0060_auto_20221115_1716'),
    ]

    operations = [
    ]
