# Generated by Django 3.2.12 on 2022-11-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_auto_20221115_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='work',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='work',
            field=models.ManyToManyField(null=True, related_name='details', to='order.Work'),
        ),
    ]
