# Generated by Django 3.2.12 on 2022-11-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0061_merge_0054_auto_20221115_1516_0060_auto_20221115_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='order_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='order.ordermaster'),
        ),
    ]
