# Generated by Django 3.2.12 on 2022-11-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0061_auto_20221116_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='work',
            field=models.ManyToManyField(related_name='details', to='order.Work'),
        ),
    ]
