# Generated by Django 3.2.12 on 2022-11-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_alter_orderdetail_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='work',
            new_name='works',
        ),
    ]
