# Generated by Django 3.2.12 on 2022-11-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_alter_work_order_master'),
        ('order', '0063_rename_work_orderdetail_works'),
    ]

    operations = [
    ]
