# Generated by Django 3.2.12 on 2022-11-16 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_merge_20221116_1015'),
        ('order', '0064_merge_20221116_1035'),
    ]

    operations = [
    ]
