# Generated by Django 3.2.12 on 2022-11-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_merge_20221116_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='state',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='details', to='order.Work'),
        ),
    ]
