# Generated by Django 3.2.12 on 2022-11-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0066_auto_20221116_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='state',
            field=models.CharField(default='작업중', max_length=15),
        ),
    ]
