# Generated by Django 3.2.12 on 2022-11-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0067_alter_work_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='memo',
            new_name='memo_by_subcontractor',
        ),
    ]
