# Generated by Django 3.2.12 on 2022-11-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_rename_memo_work_memo_by_subcontractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='memo_by_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='memo_by_pre_worker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='memo_by_subcontractor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
