# Generated by Django 3.2.12 on 2022-11-17 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0069_auto_20221116_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='works',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='order.work'),
        ),
    ]
