# Generated by Django 3.2.12 on 2022-11-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_auto_20221121_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyorder',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
