# Generated by Django 3.2.12 on 2022-11-23 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_alter_easyorder_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='easy_order', to='order.ordermaster'),
        ),
    ]
