# Generated by Django 3.2.12 on 2022-12-01 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0074_easyorderfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_details', to='order.orderdetail'),
        ),
        migrations.AlterField(
            model_name='workdetail',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_details', to='order.work'),
        ),
    ]
