# Generated by Django 3.2.12 on 2022-12-01 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0075_auto_20221201_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='order.work'),
        ),
    ]
