# Generated by Django 3.2.12 on 2022-12-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_alter_work_order_master'),
        ('order', '0076_alter_orderdetail_work'),
    ]

    operations = [
    ]
