# Generated by Django 3.2.12 on 2023-02-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_auto_20230201_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price_delivery',
        ),
    ]
