# Generated by Django 3.2.12 on 2022-12-08 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_merge_20221207_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='order_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='order.ordermaster'),
        ),
    ]
