# Generated by Django 3.2.12 on 2023-02-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0078_remove_orderdetail_price_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='is_pick_up',
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='is_pick_up',
            field=models.BooleanField(default=False),
        ),
    ]
