# Generated by Django 3.2.12 on 2022-12-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_merge_20221208_1321'),
        ('order', '0078_alter_work_order_master'),
    ]

    operations = [
    ]
