# Generated by Django 3.2.12 on 2023-02-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0079_merge_20221209_1319'),
        ('order', '0080_ordermaster_is_deleted'),
    ]

    operations = [
    ]
