# Generated by Django 3.2.12 on 2023-02-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0081_merge_20230223_1129'),
        ('order', '0081_merge_20230223_1300'),
    ]

    operations = [
    ]
