# Generated by Django 3.2.12 on 2023-03-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0082_merge_20230223_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyorder',
            name='is_order_more',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='easyorder',
            name='is_visit',
            field=models.BooleanField(default=False),
        ),
    ]
