# Generated by Django 3.2.12 on 2023-07-06 06:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0083_auto_20230324_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='student_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None),
        ),
    ]
