# Generated by Django 3.2.12 on 2023-06-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20230623_1535'),
        ('order', '0083_auto_20230324_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='new_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='product.newdraft'),
        ),
    ]
