# Generated by Django 3.2.12 on 2023-06-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0083_auto_20230324_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
