# Generated by Django 3.2.12 on 2023-06-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0084_auto_20230616_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
