# Generated by Django 3.2.12 on 2023-06-21 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_address_delivery_memo'),
        ('order', '0085_orderdetail_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='user_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_master', to='common.address'),
        ),
    ]
