# Generated by Django 3.2.12 on 2023-06-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0086_ordermaster_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='user_address',
        ),
    ]
