# Generated by Django 3.2.12 on 2023-06-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0084_orderdetail_new_draft'),
        ('order', '0087_remove_ordermaster_user_address'),
    ]

    operations = [
    ]
