# Generated by Django 3.2.12 on 2023-06-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20230623_1535'),
        ('order', '0088_merge_20230623_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetail',
            name='new_draft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to='product.newdraft'),
        ),
    ]
