# Generated by Django 3.2.12 on 2023-07-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_workdetail_new_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='parent_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='order.ordermaster'),
        ),
    ]
