# Generated by Django 3.2.12 on 2023-07-07 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_tafirm'),
        ('order', '0090_ordermaster_parent_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaOrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=25, null=True)),
                ('gym_name', models.CharField(max_length=50, null=True)),
                ('price_paid', models.IntegerField(null=True)),
                ('price_delivery', models.IntegerField(null=True)),
                ('price_to_be_paid', models.IntegerField(null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_order_masters', to='order.ordermaster')),
                ('ta_firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ta_order_masters', to='business.tafirm')),
            ],
            options={
                'db_table': 'ta_order_masters',
            },
        ),
        migrations.CreateModel(
            name='TaOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_special', models.IntegerField(null=True)),
                ('total_price_special', models.IntegerField(null=True)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_order_details', to='order.orderdetail')),
                ('ta_order_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_order_details', to='order.taordermaster')),
            ],
            options={
                'db_table': 'ta_order_details',
            },
        ),
    ]
