# Generated by Django 3.2.12 on 2023-07-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_ordermaster_parent_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='is_changed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='is_returned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
