# Generated by Django 3.2.12 on 2023-07-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_taorderdetail_taordermaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='taorderdetail',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
