# Generated by Django 3.2.12 on 2023-07-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0092_taorderdetail_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taorderdetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
