# Generated by Django 3.2.12 on 2023-07-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_auto_20230707_1146'),
        ('order', '0093_alter_taorderdetail_is_deleted'),
    ]

    operations = [
    ]
