# Generated by Django 3.2.12 on 2023-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0094_merge_20230711_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='taordermaster',
            name='state',
            field=models.CharField(default='미결제', max_length=10),
        ),
    ]
