# Generated by Django 3.2.12 on 2023-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_taordermaster_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taordermaster',
            name='price_delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taordermaster',
            name='price_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taordermaster',
            name='price_to_be_paid',
            field=models.IntegerField(),
        ),
    ]
