# Generated by Django 3.2.12 on 2023-07-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0096_auto_20230711_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='date_to_be_shipped',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_direct_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
