# Generated by Django 3.2.12 on 2023-07-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0084_alter_orderdetail_student_names'),
        ('order', '0097_auto_20230713_1537'),
    ]

    operations = [
    ]
