# Generated by Django 3.2.12 on 2023-08-02 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_draftsize'),
        ('order', '0099_ordermaster_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='new_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='product.newdraft'),
        ),
    ]
